### ISSUE TITLE
Add cross-platform CI with pnpm

### ISSUE THREAD

**Issue by NicoSchwandner** [NicoSchwandner/WorkJournal#25]
## Goal

Create a workflow that runs the full test + build matrix on every push/PR so we never merge a broken package.

## Current State

There is an existing CI workflow, but it needs modifications to match our requirements.

## Tasks

1. **Update `.github/workflows/ci.yml`**

   ```yaml
   name: CI

   on:
     push:
       branches: [main]
     pull_request:
       branches: [main]

   jobs:
     test:
       runs-on: ${{ matrix.os }}
       strategy:
         fail-fast: false
         matrix:
           os: [ubuntu-latest, macos-latest, windows-latest]
           node: [18, 20]

       steps:
         - uses: actions/checkout@v4

         - name: Set up Node & pnpm
           uses: actions/setup-node@v4
           with:
             node-version: ${{ matrix.node }}
             cache: pnpm # automatic pnpm store caching

         - run: corepack enable # makes the repo-pinned pnpm available
         - run: pnpm install --frozen-lockfile
         - run: pnpm -r run build
         - run: pnpm test
   ```

2. Make sure **`pnpm install --frozen-lockfile`** passes locally first (`pnpm i --frozen-lockfile`).

## Acceptance criteria / Definition of Done

- Workflow passes on all OS / Node versions.
- PR cannot be merged without a green check from **CI**.

## Notes

- The main differences from the existing workflow are:
  - Using `fail-fast: false` in the strategy
  - Using corepack to enable pnpm
  - Using frozen lockfiles
  - Simplifying the Node setup with automatic pnpm caching
- This issue focuses only on the CI workflow changes.
