### ISSUE TITLE
Release workflow: publish & git-tag only after green CI

### ISSUE THREAD

**Issue by NicoSchwandner** [NicoSchwandner/WorkJournal#26]
## Goal

Automate `npm publish` (via Changesets) _and_ push a Git tag, but only if the CI workflow on `main` concluded successfully.

## Current State

There is an existing release.yml workflow, but it doesn't wait for CI to complete before attempting to publish. We need to modify it to only run after successful CI.

## Tasks

1. **Update `.github/workflows/release.yml`**

   ```yaml
   name: Release

   on:
     workflow_run:
       workflows: ["CI"] # keep the name identical to ci.yml
       branches: [main]
       types: [completed]

   jobs:
     publish-and-tag:
       if: github.event.workflow_run.conclusion == 'success'
       runs-on: ubuntu-latest
       permissions:
         contents: write # required for pushing tags
         packages: write # optional (GH Packages)

       steps:
         - uses: actions/checkout@v4

         - name: Set up Node 20 + pnpm cache
           uses: actions/setup-node@v4
           with:
             node-version: "20"
             cache: pnpm
             registry-url: "https://registry.npmjs.org/"

         - run: corepack enable
         - run: pnpm install --frozen-lockfile
         - run: pnpm -r run build

         - name: Publish via Changesets
           env:
             NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: pnpm exec changeset publish

         - name: Tag git with published version
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
             version=$(jq -r '.version' packages/cli/package.json)
             git config user.name  'github-actions[bot]'
             git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
             git tag "v$version"
             git push --tags
   ```

2. **Secrets**

   - Add `NPM_TOKEN` (publish rights for `work-journal`) under _Settings → Secrets → Actions_.
   - `GITHUB_TOKEN` is provided automatically by GitHub.

3. **Verify `templates/` packaging**
   Ensure `templates/**` lives in the published tarball (already in `files` array). Test locally with `npm pack`.

4. **Smoke-test**
   After merging, watch the "Release" workflow: it should build, publish `vX.Y.Z`, and push tag `vX.Y.Z`.

## Acceptance criteria / Definition of Done

- A commit to `main` with a valid changeset triggers **Release** only after CI succeeded.
- The package appears on npm with the new version, and `git tag -l` shows the matching `vX.Y.Z`.
- Tag is visible in GitHub's _Releases_ tab.

## Note

This issue depends on Issue 1 (CI must be present), as the new release workflow leverages CI completion as a trigger.
