### ISSUE TITLE
9. CI Pipeline

### ISSUE THREAD

**Issue by NicoSchwandner** [NicoSchwandner/WorkJournal#7]
### 🎯 Goal

Run build + tests on Linux, macOS, Windows (Node 18 & 20).

### 📂 Scope

- Single GitHub Actions workflow `ci.yml`.

### 🔧 Steps

Create `.github/workflows/ci.yml`:

```yaml
name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ matrix.node }} }
      - run: pnpm install
      - run: pnpm -r run build
      - run: pnpm test
```

### ✅ Done when

- PR opens → CI passes on all six combos.
