### ISSUE TITLE
10. Release Automation

### ISSUE THREAD

**Issue by NicoSchwandner** [NicoSchwandner/WorkJournal#8]
### 🎯 Goal

Automate semantic versioning & npm publish via Changesets.

### 📂 Scope

- Changeset config + GitHub Action.

### 🔧 Steps

1. Install & init:

   ```bash
   pnpm add -D @changesets/cli
   npx changeset init
   ```

2. Root `package.json`
   ```jsonc
   { "scripts": { "version": "changeset version" } }
   ```
3. Add `.github/workflows/release.yml`
   ```yaml
   name: Release
   on:
     push:
       branches: [main]
   jobs:
     publish:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: pnpm/action-setup@v2
           with: { version: 9 }
         - uses: actions/setup-node@v4
           with:
             node-version: 18
             registry-url: "https://registry.npmjs.org"
         - run: pnpm install
         - run: pnpm run build -r
         - run: npx changeset publish
           env:
             NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   ```

### ✅ Done when

- Merging a PR with a `changeset` file triggers a `Version Packages` commit and publishes `packages/cli` to npm (dry-run acceptable in test repo).
